version: "3"
volumes:
  postgres:
services:
  postgres:
    environment:
    - POSTGRES_DB=keycloak
    - POSTGRES_USER=keycloak
    - POSTGRES_PASSWORD=password
    image: postgres:9.6
    ports:
    - 5432:5432
    volumes:
    - postgres:/var/lib/postgresql
  keycloak:
    image: jboss/keycloak:4.2.1.Final
    depends_on:
    - postgres
    environment:
    - DB_VENDOR=POSTGRES
    - KEYCLOAK_LOGLEVEL=DEBUG
    - POSTGRES_USER=keycloak
    - POSTGRES_DATABASE=keycloak
    - POSTGRES_PASSWORD=password
    - KEYCLOAK_USER=keycloak
    - KEYCLOAK_PASSWORD=password
    - POSTGRES_PORT_5432_TCP_ADDR=postgres
    - POSTGRES_PORT_5432_TCP_PORT=5432
    ports:
    - 8080:8080
