version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-7.0.1
      - test-8.0.1
  release:
    jobs:
      - test-8.0.1:
          filters:
            tags:
              only: /\d+\.\d+\.\d+(-rc.\d+)?/
            branches:
              ignore: /.*/
      - build-and-release:
          requires:
            - test-8.0.1
          filters:
            tags:
              only: /\d+\.\d+\.\d+(-rc.\d+)?/
            branches:
              ignore: /.*/

defaults:
  go_image: &go_image
    - image: circleci/golang:1.13.5

  keycloak_env: &keycloak_env
    environment:
      DB_VENDOR: H2
      KEYCLOAK_LOGLEVEL: DEBUG
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: password

  testacc_job: &testacc_job
    working_directory: /go/src/github.com/charlesderek/terraform-w-keycloak
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-cache-{{ checksum "go.sum" }}
      - run: go mod download
      - save_cache:
          key: go-cache-{{ checksum "go.sum" }}
          paths:
            - /go/pkg
      - run:
          command: |
            ./scripts/wait-for-local-keycloak.sh
            ./scripts/create-terraform-client.sh
            make testacc
    environment:
      GO111MODULE: "on"
      KEYCLOAK_CLIENT_ID: "terraform"
      KEYCLOAK_CLIENT_SECRET: "d0e0f95-0f42-4a63-9b1f-94274655669e"
      KEYCLOAK_URL: "http://localhost:8080"
      KEYCLOAK_REALM: "master"
      KEYCLOAK_TEST_PASSWORD_GRANT: "true"

jobs:
  test-7.0.1:
    docker:
      - <<: *go_image
      - image: jboss/keycloak:7.0.1
        <<: *keycloak_env
    <<: *testacc_job

  test-8.0.1:
    docker:
      - <<: *go_image
      - image: jboss/keycloak:8.0.1
        <<: *keycloak_env
    <<: *testacc_job

  build-and-release:
    docker:
      - <<: *go_image
    environment:
      GO111MODULE: "on"
    working_directory: /go/src/github.com/charlesderek/terraform-w-keycloak
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "27:1c:fb:ea:7d:89:93:bb:13:54:5b:3f:b7:cc:1b:09"
      - run: go mod download
      - run:
          command: |
            ./scripts/build-release.sh
            ./scripts/publish-release.sh

