version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-client-credentials
      - test-password
  release:
    jobs:
      - test-client-credentials:
          filters:
            tags:
              only: /\d+\.\d+\.\d+(-rc.\d+)?/
            branches:
              ignore: /.*/
      - build-and-release:
          requires:
            - test-client-credentials
          filters:
            tags:
              only: /\d+\.\d+\.\d+(-rc.\d+)?/
            branches:
              ignore: /.*/
jobs:
  test-template: &test-template
    docker:
      - image: circleci/golang:1.11.4
      - image: jboss/keycloak:4.8.3.Final
        environment:
          DB_VENDOR: H2
          KEYCLOAK_LOGLEVEL: DEBUG
          KEYCLOAK_USER: keycloak
          KEYCLOAK_PASSWORD: password
    working_directory: /go/src/github.com/charlesderek/terraform-w-keycloak
    steps:
      - checkout
      - restore_cache:
          keys:
            - {{ checksum "go.sum" }}
      - run: go mod download
      - save_cache:
          key: {{ checksum "go.sum" }}
          paths:
            - /go/pkg
      - run:
          command: |
            ./scripts/wait-for-local-keycloak.sh
            ./scripts/create-terraform-client.sh
            make testacc
  test-client-credentials:
    <<: *test-template
    environment:
      GO111MODULE: "on"
      KEYCLOAK_CLIENT_ID: terraform
      KEYCLOAK_URL: http://localhost:8080
      KEYCLOAK_REALM: master
      KEYCLOAK_CLIENT_SECRET: d0e0f95-0f42-4a63-9b1f-94274655669e
  test-password:
    <<: *test-template
    environment:
      GO111MODULE: "on"
      KEYCLOAK_CLIENT_ID: admin-cli
      KEYCLOAK_URL: http://localhost:8080
      KEYCLOAK_REALM: master
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: password
  build-and-release:
    docker:
      - image: circleci/golang:1.11.4
    working_directory: /go/src/github.com/charlesderek/terraform-w-keycloak
    steps:
      - checkout
      - run: go mod download
      - run:
          command: |
            ./scripts/build-release.sh
            ./scripts/publish-release.sh
