version: 2
workflows:
  version: 2
  test:
    jobs:
      - client-credentials
      - password
jobs:
  test-template: &test-template
    docker:
    - image: circleci/golang:1.11.4
    - image: jboss/keycloak:4.8.3.Final
      environment:
        DB_VENDOR: H2
        KEYCLOAK_LOGLEVEL: DEBUG
        KEYCLOAK_USER: keycloak
        KEYCLOAK_PASSWORD: password
    working_directory: /go/src/github.com/charlesderek/terraform-w-keycloak
    steps:
    - checkout
    - restore_cache:
        keys:
        - go-cache
    - run: go mod download
    - save_cache:
        key: go-cache
        paths:
        - /go/pkg
    - run:
        command: |
          ./scripts/wait-for-local-keycloak.sh
          ./scripts/create-terraform-client.sh
          make testacc
  client-credentials:
    <<: *test-template
    environment:
      GO111MODULE: "on"
      KEYCLOAK_CLIENT_ID: terraform
      KEYCLOAK_URL: http://localhost:8080
      KEYCLOAK_REALM: master
      KEYCLOAK_CLIENT_SECRET: d0e0f95-0f42-4a63-9b1f-94274655669e
  password:
    <<: *test-template
    environment:
      GO111MODULE: "on"
      KEYCLOAK_CLIENT_ID: admin-cli
      KEYCLOAK_URL: http://localhost:8080
      KEYCLOAK_REALM: master
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: password
