name: Build Test Image
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build-test-image.yml"
      - "test/Dockerfile"

jobs:
  build:
    needs:
      - verify
    runs-on: ubuntu-latest
    strategy:
      matrix:
        keycloak-version:
          - '21.0.1'
          - '20.0.5'
          - '19.0.2'
      fail-fast: false
    concurrency:
      group: docker-build-${{ matrix.keycloak-version }}
      cancel-in-progress: true
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: charlesderek/keycloak-dev:${{ matrix.keycloak-version }}
          file: test/Dockerfile
          build-args: |
            KEYCLOAK_VERSION=${{ matrix.keycloak-version }}
